version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
    steps:
      - checkout
      - run:
          name: restore packages
          command: dotnet restore
      - run:
          name: build
          command: dotnet build
      - run:
          name: run unit tests
          command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - run:
          name: upload coverage reports
          command: bash <(curl -s https://codecov.io/bash)

      

